import { ArrowRight, Check, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { CtaBand, FaqSection } from '../components/PageSections';
import { NightToDawnField } from '../components/home/NightToDawnField';
import { operationsCategories, operationsFaqs, operationsFlow } from '../content/operations';

export default function Operations() {
  return <div className="detail-page"><NightToDawnField><section className="px-6 pb-14 pt-28 md:pb-20 md:pt-36"><div className="mx-auto max-w-6xl text-center"><p className="micro-label text-ink-muted">LYCORE Operations</p><h1 className="mx-auto mt-5 max-w-4xl font-display text-4xl font-medium leading-[.98] tracking-tight text-white md:text-6xl">AI operations for service businesses</h1><p className="mx-auto mt-6 max-w-3xl text-lg font-light leading-relaxed text-ink-muted">Automate the repetitive work between your customers, staff and existing software.</p><div className="detail-actions"><Link to="/contact" className="btn-primary">Book a workflow audit</Link><a href="#operations-flow" className="btn-secondary">See the workflow</a></div><div className="mt-10 rounded-[1.75rem] border border-white/15 bg-white/[.045] p-7 text-left md:p-10"><p className="text-xl font-light leading-relaxed text-white">The customer may be booked, but the work is not finished. Someone still has to create the job, update records, notify the team, send customer updates, follow up on estimates, chase payments and ask for the review. LYCORE automates the repeatable parts of that process.</p></div></div></section>
    <section id="operations-flow" className="border-t border-white/10 px-6 py-14 md:py-20"><div className="mx-auto max-w-7xl"><p className="micro-label text-ink-muted">One connected route</p><h2 className="section-title mt-4 text-white">From booked customer to completed job.</h2><ol className="mt-8 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{operationsFlow.map((step,index)=><li key={step} className="rounded-2xl border border-white/15 bg-white/[.04] p-5"><span className="text-xs text-accent">{String(index+1).padStart(2,'0')}</span><p className="mt-3 text-white">{step}</p></li>)}</ol></div></section>
    <section className="px-6 pb-14 md:pb-20"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-2">{operationsCategories.map(category=><article key={category.title} className="rounded-3xl border border-white/15 bg-white/[.04] p-7"><p className="micro-label text-accent">Operations layer</p><h2 className="mt-3 font-display text-3xl text-white">{category.title}</h2><ul className="mt-6 grid gap-3 sm:grid-cols-2">{category.items.map(item=><li key={item} className="flex gap-2 text-ink-muted"><Check className="mt-1 h-4 w-4 shrink-0 text-accent" />{item}</li>)}</ul></article>)}</div></div></section>
    <section className="px-6 pb-14 md:pb-20"><div className="mx-auto max-w-7xl rounded-3xl border border-teal/30 bg-teal/[.08] p-8 md:p-10"><ShieldCheck className="h-8 w-8 text-teal" aria-hidden="true" /><p className="micro-label mt-6 text-teal">Human control</p><h2 className="mt-3 font-display text-3xl text-white">Automate the repeatable work. Keep people in control of decisions that matter.</h2><p className="mt-5 max-w-3xl leading-relaxed text-ink-muted">AI can collect information, summarize, update systems, send routine messages, trigger workflows and prepare drafts. People remain responsible for pricing, approvals, unusual situations, sensitive conversations, technical judgment and final decisions.</p><Link to="/contact" className="btn-primary mt-7">Map your customer journey <ArrowRight className="h-4 w-4" /></Link></div></section>
    <FaqSection faqs={operationsFaqs} showAllLink={false} /><CtaBand /></NightToDawnField></div>;
}
