import { ArrowRight, Check, Workflow } from 'lucide-react';
import { Link } from 'react-router-dom';
import { operationsFlow } from '../../content/operations';

export default function OperationsBridge() {
  return <section className="border-t border-white/10 px-6 py-16 md:py-24" aria-labelledby="operations-bridge-title"><div className="mx-auto max-w-7xl">
    <div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="micro-label text-ink-muted">After the booking</p><h2 id="operations-bridge-title" className="section-title mt-4 text-white">The paperwork after the call is a leak too.</h2></div><p className="max-w-2xl text-lg font-light leading-relaxed text-ink-muted">Most owners lose time after the booking as well: updating the job, texting the customer, chasing the invoice. LYCORE can take some of that off you, depending on the tools you already use.</p></div>
    <ol className="mt-10 grid gap-3 sm:grid-cols-3 lg:grid-cols-9">{operationsFlow.map((step, index) => <li key={step} className="rounded-2xl border border-white/15 bg-white/[.04] p-4"><span className="text-xs text-accent">{String(index + 1).padStart(2, '0')}</span><p className="mt-3 text-sm leading-relaxed text-white">{step}</p></li>)}</ol>
    <div className="mt-10 grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-accent/40 bg-accent/[.09] p-7"><Workflow className="h-7 w-7 text-accent" aria-hidden="true" /><p className="micro-label mt-7 text-accent">LYCORE Front Office</p><h3 className="mt-3 font-display text-3xl text-white">Capture the opportunity.</h3><p className="mt-4 text-ink-muted">AI receptionist, booking, missed-call texts, follow-up and websites built to get the phone call.</p><p className="mt-6 flex items-center gap-2 text-sm font-medium text-white"><Check className="h-4 w-4 text-accent" /> Answer faster and keep good leads from going cold.</p></article><article className="rounded-3xl border border-white/15 bg-white/[.04] p-7"><Workflow className="h-7 w-7 text-teal" aria-hidden="true" /><p className="micro-label mt-7 text-teal">LYCORE Operations</p><h3 className="mt-3 font-display text-3xl text-white">Run what happens next.</h3><p className="mt-4 text-ink-muted">Job records, staff notifications, customer updates, estimate and invoice reminders and reporting, where your tools can be connected. We check what connects before anything is agreed.</p><p className="mt-6 flex items-center gap-2 text-sm font-medium text-white"><Check className="h-4 w-4 text-teal" /> Less admin after the customer says yes.</p></article></div>
    <Link to="/ai-operations" className="btn-secondary mt-8">See how the back office works <ArrowRight className="h-4 w-4" /></Link>
  </div></section>;
}
