import type { Faq, PageMeta } from '../siteData';
import { serviceEvidence } from './serviceEvidence';
import { industryFaqs, industryPlaybooks } from './industryPlaybooks';

export type GrowthPage = PageMeta & {
  eyebrow: string;
  problem: string;
  builds: string[];
  workflow: string[];
  control: string;
  related: string[];
  faqs: Faq[];
};

const standardFaqs: Faq[] = [
  { question: 'Does LYCORE replace the software we already use?', answer: 'No. LYCORE starts with the tools and operating rules your team already uses, then evaluates practical ways to connect the work around them.' },
  { question: 'Are outcomes guaranteed?', answer: 'No. A system can improve the speed and consistency of a process, but LYCORE does not guarantee rankings, reply rates, booked appointments, revenue, or any other business outcome.' },
];

const service = (slug: string, title: string, description: string, problem: string, builds: string[], workflow: string[], related: string[], seo?: { title?: string; h1?: string }): GrowthPage => ({
  path: `/services/${slug}`,
  label: title,
  title: seo?.title ?? `${title} - LYCORE`,
  description,
  h1: seo?.h1 ?? title,
  kind: 'service',
  updatedAt: '2026-09-11',
  eyebrow: 'Service system',
  problem,
  builds,
  workflow,
  control: 'Your team keeps control of business rules, escalation decisions, approvals, customer data, and the tools it chooses to keep. LYCORE configures and documents the workflow around those rules.',
  related,
  faqs: [...(serviceEvidence[slug]?.faqs || []), ...standardFaqs],
});

export const serviceGrowthPages: GrowthPage[] = [
  service('outbound-lead-generation', 'B2B outbound lead generation', 'B2B prospect research, cold email outreach, reply qualification and appointment-setting workflows for service businesses.', 'When there is no repeatable acquisition process, growth depends on referrals and whatever leads happen to arrive.', ['Target-market and account definition', 'Prospect research and list quality checks', 'Outreach sequences and reply-routing rules'], ['Target market defined', 'Relevant companies researched', 'Contacts verified where possible', 'Outreach and follow-up sent', 'Replies qualified', 'Qualified conversations booked'], ['/services/cold-email-infrastructure', '/services/crm-automation']),
  service('cold-email-infrastructure', 'Cold email infrastructure setup', 'Sending domains, business inboxes, SPF, DKIM and DMARC setup, plus about two weeks of initial email warm-up before launch checks.', 'A campaign cannot be judged fairly when domains, inboxes, authentication, and sending practices are not prepared.', ['Sending-domain strategy', 'Google Workspace or Microsoft 365 inbox setup', 'SPF, DKIM and DMARC configuration support', 'Mailbox warm-up and sending controls'], ['Sending domains and provider policies reviewed', 'Business mailboxes and authentication configured', 'Initial inbox warm-up planned for about two weeks', 'Test results and campaign rules reviewed before launch', 'Campaign sending starts gradually with monitoring', 'Replies, opt-outs and exceptions reach the right owner'], ['/services/outbound-lead-generation']),
  service('ai-receptionist', 'AI Answering Service & Receptionist', 'A 24/7 AI receptionist that answers every call, screens out wrong numbers and sales calls, qualifies real customers and books them by your rules.', 'Between marketers, wrong numbers and one-off questions, most of the calls that break your day are not the customer you want, and the customer you do want tends to call while you are already on a job. Miss that call and they ring the next business on the list. Your receptionist answers every call in your business name, screens out the noise, captures and qualifies the real enquiries, and books them in where your calendar is connected or passes them to you, nights and weekends included, without a vacation or a sick day.', ['A greeting in your business name, with answers to the questions you get asked most', 'The intake questions that tell a real job from a time-waster', 'Clear rules for when to book, when to put a caller through to a person, and when to take a message', 'Call summaries and booking alerts sent to you or your team'], ['A customer calls, day or night', 'The receptionist answers in your business name and says it is an AI assistant', 'It captures the details and qualifies the request', 'It books the job where your calendar is connected, or routes a callback request by your rules', 'The customer gets a confirmation', 'You get the caller and a clear summary'], ['/services/missed-call-text-back', '/services/lead-follow-up'], { title: 'AI Receptionist & 24/7 Answering Service - LYCORE' }),
  service('missed-call-text-back', 'Missed Call Text Back Service', 'A missed call text back service that texts the caller right after an unanswered call, so the job does not go to the next business on the list.', 'You cannot pick up on a roof, under a sink or with a patient in the chair. Invoca, a call analytics company, reports that 27% of calls to home-services businesses go unanswered, and that fewer than 3% of callers sent to voicemail leave a message. So most callers who reach voicemail hang up without ever saying who they are. A missed call text back answers that silence. Right after an unanswered call, the caller gets a short text from your business asking what they need, so the conversation can start before they dial the next number.', ['A text sent automatically when a call goes unanswered', 'A message in your own words, approved by you, with opt-out handling built in', 'Replies routed to you or your team with the caller\'s details captured', 'A simple prompt for the caller to describe the job or book a time'], ['A call comes in and nobody can pick up', 'The caller gets your approved text', 'They reply with what they need', 'The request is captured with their details', 'You or your team are notified', 'The job is booked or a callback is set'], ['/services/ai-receptionist', '/services/lead-follow-up'], { title: 'Missed Call Text Back Service for Service Businesses - LYCORE' }),
  service('lead-follow-up', 'Lead Follow-Up Automation', 'Lead follow-up automation that replies to every enquiry, chases estimates and reminds customers, then hands over to a person when it matters.', 'Plenty of enquiries go quiet, not because the customer said no, but because nobody followed up. The form nobody answered that day, the estimate nobody chased, the customer who said they would think about it. Lead follow-up automation replies to every enquiry, follows up on estimates and appointment requests on a schedule you approve, and stops the moment the customer replies or a person needs to take over.', ['An instant reply to every new enquiry, so nobody is left waiting', 'Estimate and appointment reminders that go out without you remembering', 'A task for you or your team the moment automation should stop and a person should step in', 'Timing and channel rules you approve, including quiet hours and opt-outs'], ['A lead arrives by call, form or message', 'They get an acknowledgement straight away', 'Follow-up continues on your approved schedule', 'A reply or status change is recorded', 'A person is asked to step in when needed', 'You can see what happened to each lead'], ['/services/crm-automation', '/services/customer-reactivation'], { title: 'Lead Follow-Up Automation for Service Businesses - LYCORE' }),
  service('reputation-management', 'Reputation Management', 'Practical review and reputation workflows for service businesses.', 'Completed jobs rarely become reviews without a consistent, customer-respectful request process.', ['Reputation-channel review', 'Review-request process design', 'Response workflow guidance', 'Performance and operational monitoring'], ['Job completes', 'Completion signal is received', 'Review request is sent', 'Configured follow-up occurs', 'Review is received', 'Response workflow is available'], ['/services/review-automation', '/services/google-business-profile-management']),
  service('review-automation', 'Review Automation', 'Post-service review-request workflows built around the customer journey.', 'Asking manually is inconsistent; avoiding the request entirely leaves a business without fresh customer feedback.', ['Completion-based triggers', 'SMS or email request paths', 'Respectful follow-up timing', 'Review-response routing'], ['Job completes', 'Customer is identified', 'Request is sent', 'No response receives configured follow-up', 'Review arrives', 'Team is notified'], ['/services/reputation-management']),
  service('google-business-profile-management', 'Google Business Profile Management Services', 'Google Business Profile management: the right phone number, hours, categories and service area, so customers who find you on Google reach you.', 'For many local searches your Google Business Profile is the first thing a customer sees, before your website. If the phone number is wrong, the hours are out of date, or the service area is missing, a customer who was ready to call reaches the wrong place or gives up. We check the profile against your website and other listings, correct what is wrong, and keep it accurate, so the details that decide a call are right.', ['A full check of your profile against your website and other listings', 'Correct phone number, hours, categories and service area', 'Photos, posts and Q&A so the profile looks active and trustworthy', 'A profile that sends customers to the right call or booking path'], ['Profile checked against your other listings', 'Wrong or missing details corrected', 'Services and service area reviewed', 'Call and booking path checked', 'Updates scheduled', 'Changes monitored'], ['/services/reputation-management', '/services/web-design'], { title: 'Google Business Profile Management Services - LYCORE' }),
  service('crm-automation', 'CRM Automation', 'Customer lifecycle workflows around the CRM and operational tools your team already uses.', 'Leads, estimates, reminders and internal handoffs break when systems are disconnected or steps are manual.', ['Pipeline and lifecycle review', 'Lead assignment and notification rules', 'API, webhook, native or automation-platform connection assessment', 'Documented exception handling'], ['Trigger occurs', 'Data is routed', 'Customer or team message is sent', 'Status is updated', 'Exception is assigned to a person', 'Workflow is reviewed'], ['/services/lead-follow-up', '/services/customer-reactivation']),
  service('customer-reactivation', 'Customer Reactivation', 'Reactivation workflows for past customers, dormant leads, and recurring-service reminders.', 'Past customers can be forgotten even when they are the most likely people to need the next service.', ['Eligible customer segments', 'Approved outreach cadence', 'Response and booking path', 'Suppression and opt-out handling'], ['Segment is selected', 'Message is approved', 'Campaign is sent', 'Replies are routed', 'Bookings are handled', 'Results are reviewed'], ['/services/crm-automation']),
  service('web-design', 'Web Design for Service Businesses', 'A fast, phone-first website for service businesses that makes it obvious what you do, why to trust you, and how to call or book in one tap.', 'Your website speaks for you when you are not in the room. It is the first thing a customer judges you on. If the number is hard to find, the page is slow on a phone, or it never says who you serve and where, the visitor leaves and calls a business whose site did. A good site shows how serious you are before anyone speaks to you, then makes the next step one tap.', ['Pages that say plainly what you do, who you serve and where', 'A phone number and booking button that work in one tap on a phone', 'Fast loading, because visitors leave slow pages', 'Call and form tracking, so you can see which pages bring enquiries'], ['A visitor arrives from Google or a referral', 'They see what you do and where within seconds', 'They see why to trust you', 'They call or book in one tap', 'You or your receptionist capture the enquiry', 'Follow-up begins'], ['/services/lead-follow-up', '/services/google-business-profile-management'], { title: 'Web Design for Contractors & Service Businesses - LYCORE' }),
];

// Search-facing titles for industries where buyers search "answering service for X" / "AI receptionist for X".
// Keyword volumes and difficulty checked in Semrush (US), 2026-09-18.
const industrySeoTitles: Record<string, { title: string; h1: string }> = {
  plumbing: { title: 'Answering Service for Plumbers: 24/7 Call Answering - LYCORE', h1: 'Answering service for plumbers' },
  hvac: { title: 'Answering Service for HVAC Companies - LYCORE', h1: 'Answering service for HVAC companies' },
  dentists: { title: 'Answering Service for Dentists - LYCORE', h1: 'Answering service for dental practices' },
  'law-firms': { title: 'AI Receptionist & Answering Service for Law Firms - LYCORE', h1: 'AI receptionist and answering service for law firms' },
  'home-services': { title: 'Answering Service for Contractors - LYCORE', h1: 'Answering service for contractors and home-service businesses' },
  roofing: { title: 'Answering Service for Roofers - LYCORE', h1: 'Answering service for roofers' },
  'real-estate': { title: 'AI Receptionist for Real Estate Agents - LYCORE', h1: 'AI receptionist for real estate agents' },
  'med-spas': { title: 'Answering Service for Med Spas - LYCORE', h1: 'Answering service for med spas' },
  restoration: { title: 'Answering Service for Restoration Companies - LYCORE', h1: 'Answering service for water damage and restoration companies' },
  locksmiths: { title: 'Answering Service for Locksmiths - LYCORE', h1: 'Answering service for locksmiths' },
};

const industry = (slug: string, name: string, description: string, problem: string, workflow: string[], tools: string[]): GrowthPage => ({
  path: `/industries/${slug}`,
  label: `${name} systems`,
  title: industrySeoTitles[slug]?.title ?? `${industryPlaybooks[slug]?.headline || `${name} workflows`} - LYCORE`,
  description,
  h1: industrySeoTitles[slug]?.h1 ?? (industryPlaybooks[slug]?.headline || `${name} workflows`),
  kind: 'industry',
  updatedAt: '2026-09-11',
  eyebrow: 'Industry workflow',
  problem,
  builds: [...(industryPlaybooks[slug]?.workflows.map(item => item.name) || [workflow[1], workflow[3]]), 'Documented human handoffs and exception rules', 'Software connection review before the build is agreed'],
  workflow,
  control: industryPlaybooks[slug]?.boundary || 'Your staff approves the business rules and owns professional decisions.',
  related: [...(industryPlaybooks[slug]?.related || ['/services/crm-automation']), '/integrations'],
  faqs: [...industryFaqs(slug, name), ...standardFaqs],
});

export const industryGrowthPages: GrowthPage[] = [
  industry('spas', 'Spas & wellness studios', 'Booking, appointment reminders and return-visit follow-up for spas and wellness studios.', 'A therapist cannot answer every enquiry during a treatment. Questions about availability and packages need a clear booking path while the team works.', ['Guest asks about a treatment or package', 'Preferred service and timing recorded', 'Appointment request sent to the booking team', 'Guest receives confirmation and preparation details', 'Reminder offers a way to reschedule', 'Guest receives an approved return-visit invitation'], []),
  industry('real-estate', 'Real estate agents', 'AI receptionist for real estate agents: answers every enquiry while you are at a viewing, captures the property and contact details, and sends it to you.', 'You are at a showing when a buyer calls about your listing, and they may call the next agent if you do not pick up. An AI receptionist answers every enquiry, records the property and what the caller is looking for, and hands you the details so you can follow up first.', ['Property enquiry arrives', 'Property reference and contact details captured', 'Buying or selling intent and timing recorded', 'Viewing or valuation request assigned to an agent', 'Agent receives the conversation history', 'Follow-up changes when the client responds'], []),
  industry('law-firms', 'Lawyers & law firms', 'AI receptionist and answering service for law firms: answers every call, captures contact details and the type of matter, and routes the enquiry to your intake team.', 'A person looking for a lawyer is often in a hurry and calls several firms. If your line rings out, they may retain someone else. An AI receptionist answers every call, captures contact details and the broad type of matter, and routes it to your intake team. It gives no legal advice and does not decide whether the firm takes a case. Your staff do.', ['Prospective client contacts the firm', 'Contact details and broad matter type recorded', 'Request reaches the designated intake team', 'Staff completes its suitability and conflict review', 'Approved consultation time is offered', 'Reminder and callback task reach the assigned person'], []),
  industry('hvac', 'HVAC', 'Answering service for HVAC companies: call answering that captures the address and issue and follows your priority rules, so no-heat calls do not hit voicemail.', 'When the first cold night hits, no-heat calls arrive all at once while your technicians are already on jobs, and voicemail loses them. An AI receptionist answers every call, captures the address and what the equipment is doing, applies your escalation rules and sends dispatch a clear summary, so the calls that matter reach you first and the rest are booked for a callback.', ['Customer reports heating or cooling issue', 'Property and equipment details recorded', 'Urgent concerns follow team escalation rules', 'Service or estimate request assigned', 'Appointment reminder sent', 'Maintenance follow-up scheduled with permission'], []),
  industry('electrical', 'Electrical contractors', 'Service enquiry capture, electrician callbacks and estimate follow-up for electrical contractors.', 'Electrical enquiries range from routine installation quotes to urgent concerns. A generic callback list does not tell staff which request needs attention first.', ['Customer describes the service request', 'Location and contact details captured', 'Urgent concerns routed under approved rules', 'Electrician reviews request', 'Visit or estimate appointment confirmed', 'Quote follow-up assigned'], []),
  industry('locksmiths', 'Locksmiths', 'Answering service for locksmiths: an AI receptionist that answers lockout calls, captures the location, and hands your technician a callback request.', 'Someone locked out of their car or home at night is calling every locksmith they can find, and they book the first one who picks up. An AI receptionist answers every call, captures where they are and what is locked, checks your service area and gives your technician a clear callback request.', ['Lockout request received', 'Location and lock context captured', 'Service area checked', 'Technician receives callback request', 'Team confirms availability and price', 'Customer receives the agreed next step'], []),
  industry('auto-repair', 'Auto repair shops', 'Vehicle enquiry intake, workshop booking and repair-update workflows for auto repair shops.', 'A workshop cannot stop a repair every time the phone rings. Vehicle details and the reason for the call need to reach the right staff member.', ['Customer contacts the shop', 'Vehicle and concern recorded', 'Service advisor receives the request', 'Inspection appointment confirmed', 'Team-approved update sent', 'Collection or future service reminder prepared'], []),
  industry('restaurants', 'Restaurants', 'Reservation requests, guest questions and overflow call workflows for restaurants.', 'The dinner rush is also a busy time for calls. Reservation details and guest questions need to reach the host without interrupting every table.', ['Guest calls during service', 'Date, party size and contact details captured', 'Reservation rules checked', 'Host confirms available table or callback', 'Guest receives confirmation', 'Changes route back to the host'], []),
  industry('bail-bonds', 'Bail bond agencies', 'After-hours enquiry intake and agent callbacks for bail bond agencies.', 'A family calling outside office hours needs a calm handoff to an agent. Missing facility or contact information delays that conversation.', ['Family contacts agency', 'Caller and facility details recorded', 'Request assigned using agency rules', 'Licensed agent notified', 'Agent handles advice and eligibility', 'Callback status recorded'], []),
  industry('urgent-care', 'Urgent care clinics', 'Administrative call handling and staff handoffs for urgent care clinics.', 'Front-desk teams handle arrivals and calls at the same time. Hours, directions and administrative questions need a clear response path.', ['Caller contacts clinic', 'Administrative question identified', 'Approved hours and location information supplied', 'Clinical questions directed to staff', 'Callback details sent to front desk', 'Staff records the next action'], []),
  industry('home-services', 'Home services', 'Answering service for contractors: a 24/7 AI receptionist that answers every call, captures the job and books or routes it while you are on site.', 'You cannot answer the phone and do the job at the same time, and a homeowner with an urgent problem calls the next contractor on the list. An AI receptionist answers every call, filters out the wrong numbers and sales calls, captures the job and location, and books it or passes it to you.', ['Enquiry arrives', 'Service need and location captured', 'Availability or escalation rules checked', 'Request routed or booked', 'Customer confirmed', 'Follow-up continues'], ['Jobber', 'Housecall Pro', 'ServiceTitan']),
  industry('pest-control', 'Pest control', 'Customer-journey systems for pest-control enquiries, recurring service and reviews.', 'A treatment request can be lost between the first call, scheduling, job completion, and the next seasonal need.', ['Customer asks about treatment', 'Pest and property details captured', 'Service area checked', 'Appointment path offered', 'Job completion triggers review opportunity', 'Future treatment reminder is available'], ['GorillaDesk', 'FieldRoutes', 'PestPac', 'Jobber']),
  industry('plumbing', 'Plumbing', 'Answering service for plumbers: an AI receptionist that answers every call, captures the job and address, and gets urgent leaks to your on-call team.', 'A burst pipe does not wait for you to finish the job you are on. The homeowner calls one plumber, then the next, and books whoever answers. An AI receptionist answers every call in your business name, captures the address and the problem, follows your urgency rules and reaches your on-call team, so the emergency call becomes your job and not the next plumber\'s.', ['Customer calls with an issue', 'Location and issue captured', 'Urgency and escalation rules checked', 'On-call team notified or visit booked', 'Customer receives confirmation', 'Completed work can start a review workflow'], ['Housecall Pro', 'Jobber', 'ServiceTitan']),
  industry('roofing', 'Roofing', 'Answering service for roofers: an AI receptionist that answers storm-season calls, captures the damage and address, and logs inspection requests.', 'After a storm the phone does not stop, and you are up on a roof. Homeowners call several roofers and talk to whoever answers. An AI receptionist answers every call, captures the address and the damage and logs an inspection request, so the work is waiting for you when you climb down.', ['Property owner enquires', 'Damage and location captured', 'Inspection request logged', 'Estimator or booking path assigned', 'Estimate follow-up begins', 'Customer status is reviewed'], ['Jobber', 'ServiceTitan', 'HubSpot']),
  industry('restoration', 'Water damage & restoration', 'Answering service for water damage and restoration companies: 24/7 call answering that captures the loss, location and urgency and alerts your response team.', 'Water damage does not wait until morning, and neither does the customer. Someone with a flooded basement keeps calling until a company picks up. An AI receptionist answers at any hour, captures the type of loss, the location and how urgent it is, applies your escalation rules and alerts your response team, so the job is yours before they dial the next company.', ['Damage call arrives', 'Type, location and urgency captured', 'Escalation rules checked', 'Response team notified', 'Customer updated', 'Job lifecycle follow-up continues'], ['ServiceTitan', 'Jobber', 'HubSpot']),
  industry('towing', 'Towing', 'Dispatch-ready intake and customer communication workflows for towing businesses.', 'A stranded driver may call several providers in minutes; response speed and precise location capture matter.', ['Driver calls', 'Location and vehicle details captured', 'Dispatch rules checked', 'Driver or team notified', 'Customer receives next-step update', 'Follow-up records the outcome'], ['Google Calendar', 'Twilio', 'HubSpot']),
  industry('med-spas', 'Med spas', 'Answering service for med spas: an AI receptionist that answers consultation calls, answers approved questions and offers times while your team is with clients.', 'Your team is with a client, so consultation calls go to voicemail, and someone comparing med spas moves on to the one that answered. An AI receptionist answers every call in your spa\'s name, answers only what you have approved, captures what the caller is interested in and offers a consultation time or a callback.', ['Prospect enquires', 'Consultation request captured', 'Approved qualification questions answered', 'Available appointment path offered', 'Reminder workflow begins', 'Reactivation can be considered'], ['Boulevard', 'Vagaro', 'Mindbody', 'Mangomint', 'Zenoti']),
  industry('dentists', 'Dental practices', 'Answering service for dentists: an AI receptionist answers non-clinical patient calls, captures appointment requests and passes clinical questions to staff.', 'Your front desk is checking in a patient while the phone rings. A new patient who reaches voicemail may try the next practice, and an existing patient waits for an answer to a simple question. An AI receptionist answers non-clinical calls, captures appointment requests and details, and sends anything clinical straight to your staff.', ['Patient enquiry arrives', 'Non-clinical details captured', 'Appointment or callback path offered', 'Reminder sent', 'Staff receives summary', 'Recall or reactivation workflow is considered'], ['Dentrix', 'Open Dental', 'Eaglesoft', 'Curve Dental']),
  industry('veterinary', 'Veterinary practices & pet clinics', 'Non-clinical lead response, scheduling and follow-up systems for veterinary practices.', 'A worried pet owner needs an immediate, clear next step when the team is busy with patients.', ['Pet owner enquires', 'Non-clinical details captured', 'Urgent escalation rules checked', 'Appointment or callback path offered', 'Reminder is sent', 'Team receives the summary'], ['Google Calendar', 'HubSpot', 'Twilio']),
];

const integration = (slug: string, name: string, category: string, description: string, workflows: string[]): GrowthPage => ({
  path: `/integrations/${slug}`,
  label: `${name} workflows`,
  title: `${name} Automation & Workflow Integration — LYCORE`,
  description,
  h1: `${name} automation and workflow integration`,
  kind: 'integration',
  updatedAt: '2026-09-11',
  eyebrow: `${category} integration`,
  problem: `A ${name} workflow can become disconnected when customer information, notifications, and follow-up must be copied between tools.`,
  builds: ['A discovery review of available connection methods', 'Workflow design around approved business rules', 'Clear documentation of limitations and human handoffs'],
  workflow: workflows,
  control: `LYCORE is not an official ${name} partner and does not claim a native connection without verification. Connection options may rely on the platform's available features, APIs, webhooks, Zapier, Make, n8n, or custom implementation.`,
  related: ['/services/crm-automation', '/services/lead-follow-up', '/integrations'],
  faqs: [{ question: `Does LYCORE replace ${name}?`, answer: `No. LYCORE evaluates whether workflows can be built around ${name}; it does not present the service as a replacement for the platform.` }, ...standardFaqs],
});

export const integrationGrowthPages: GrowthPage[] = [
  integration('gohighlevel', 'GoHighLevel', 'CRM', 'GoHighLevel workflow planning for service-business customer journeys.', ['Lead arrives', 'Contact is created or matched', 'Assigned workflow begins', 'Team is notified', 'Booking or follow-up status is recorded']),
  integration('housecall-pro', 'Housecall Pro', 'Field-service', 'Housecall Pro workflow assessment for leads, jobs and customer communication.', ['Customer request is captured', 'Connection method is assessed', 'Job or customer workflow is routed', 'Team receives notification', 'Post-job follow-up is considered']),
  integration('gorilladesk', 'GorillaDesk', 'Field-service', 'GorillaDesk workflow assessment for pest-control customer journeys.', ['Treatment enquiry is captured', 'Connection method is assessed', 'Scheduling or job context is routed', 'Completion signal is reviewed', 'Review or reminder workflow is considered']),
  integration('fieldroutes', 'FieldRoutes', 'Field-service', 'FieldRoutes workflow assessment for customer acquisition and follow-up.', ['Lead or customer event occurs', 'Available connection method is reviewed', 'Approved data is routed', 'Team notification is sent', 'Lifecycle follow-up is considered']),
  integration('pestpac', 'PestPac', 'Field-service', 'PestPac workflow assessment for pest-control operations and customer follow-up.', ['Customer request occurs', 'System capabilities are verified', 'Approved workflow is mapped', 'Exception reaches a person', 'Outcome is recorded']),
  integration('jobber', 'Jobber', 'Field-service', 'Jobber workflow assessment for service-business leads, jobs and customer communication.', ['New request enters the journey', 'Connection method is reviewed', 'Assignment or notification occurs', 'Job status is considered', 'Customer follow-up is available']),
  integration('servicetitan', 'ServiceTitan', 'Field-service', 'ServiceTitan workflow assessment for service-business customer lifecycle workflows.', ['Lead or call event occurs', 'Integration option is verified', 'Approved data movement is configured', 'Team action is assigned', 'Result is reviewed']),
  integration('hubspot', 'HubSpot', 'CRM', 'HubSpot workflow design for service-business lead response and customer follow-up.', ['Contact enters HubSpot', 'Lifecycle stage is set', 'Workflow is triggered', 'Owner is notified', 'Outcome is logged']),
  integration('n8n', 'n8n', 'Automation', 'n8n workflow design for connecting approved service-business systems.', ['Trigger is received', 'Data is validated', 'Approved actions run', 'Exception is logged', 'Human owner is notified']),
  integration('zapier', 'Zapier', 'Automation', 'Zapier workflow assessment for practical, maintainable service-business automation.', ['Event starts a Zap', 'Approved data is passed', 'Destination action occurs', 'Failure path is defined', 'Owner reviews exceptions']),
  integration('make', 'Make', 'Automation', 'Make scenario design for service-business workflow automation.', ['Scenario trigger occurs', 'Data is transformed where approved', 'Connected action runs', 'Error handling applies', 'Workflow is monitored']),
  integration('notion', 'Notion', 'Productivity', 'Notion workflow assessment for internal visibility and documented service-business processes.', ['Operational event occurs', 'Approved summary is created', 'Team can review context', 'Task or owner is assigned', 'Process stays documented']),
];

export const growthPages = [...serviceGrowthPages, ...industryGrowthPages, ...integrationGrowthPages];

export const integrationsHub: PageMeta = {
  path: '/integrations', label: 'Integrations', title: 'Service Business Integrations & Workflow Connections — LYCORE', description: 'Explore LYCORE workflow integration assessments for field-service tools, CRMs and automation platforms.', h1: 'Work with the tools you know.', kind: 'integration', updatedAt: '2026-09-11',
};

export type ResourcePage = PageMeta & {
  answer: string;
  steps: string[];
  tradeoffs: string[];
  related: string[];
  faqs: Faq[];
};

const guide = (slug: string, title: string, description: string, answer: string, steps: string[], tradeoffs: string[], related: string[], updatedAt = '2026-09-11'): ResourcePage => ({
  path: `/resources/${slug}`, label: title, title: `${title} — LYCORE`, description, h1: title, kind: 'resource', updatedAt, answer, steps, tradeoffs, related,
  faqs: [{ question: 'Is there one right option for every business?', answer: 'No. The useful choice depends on the customer journey, the team that owns the work, the existing software, the risk of an error, and the ability to maintain the process.' }, { question: 'Can LYCORE help evaluate the workflow?', answer: 'Yes. LYCORE can review the customer journey and identify where a practical connection, automation, or human handoff may help. It does not guarantee a specific technical outcome.' }],
});

export const resourcePages: ResourcePage[] = [
  guide('how-to-stop-missing-calls-small-business', 'How to stop missing calls as a small business', 'Practical ways to stop losing customers to missed calls: find the gaps, cover them, and follow up fast.', 'You cannot answer every call while you work, so the fix is to cover the gaps rather than try harder. Find out when and how often you miss calls, then choose the cover that fits: an AI receptionist for after-hours and busy periods, a missed call text back for anything that still goes unanswered, and a follow-up routine so no enquiry goes quiet. Invoca, a call analytics company, reports that 27% of calls to home-services businesses go unanswered and that fewer than 3% of callers sent to voicemail leave a message, so voicemail alone will not catch most of them (source: invoca.com, "How much missed sales calls cost home-services businesses").', ['Check your phone records for a few weeks and note when calls go unanswered', 'Put a rough dollar value on one lost job, using the calculator with cautious numbers', 'Sort missed calls into real enquiries and wrong numbers or sales calls', 'Cover the gaps: after hours, lunch and the busy periods when you are on a job', 'Send an immediate text to anyone whose call goes unanswered', 'Follow up on every enquiry and estimate until the customer answers', 'Review the numbers after a month and adjust'], ['Answering every call yourself is not realistic while you are on a job.', 'Voicemail catches very few callers, because most do not leave a message.', 'An AI receptionist needs careful setup and clear rules for when to hand over to a person.', 'No tool guarantees more booked jobs. Measure your own results.'], ['/services/ai-receptionist', '/services/missed-call-text-back', '/resources/missed-call-text-back-calculator', '/services/lead-follow-up'], '2026-09-18'),
  guide('missed-call-text-back-for-home-services', 'Missed call text back for plumbers, HVAC and roofers', 'How a missed call text back works for plumbers, HVAC companies and roofers, what to say in the text, and what it cannot do.', 'When you are on a job and a call goes unanswered, a missed call text back sends the caller a short text from your business within moments. For plumbers, HVAC companies and roofers, where the caller often has an urgent problem and is ringing several companies, that text can keep the conversation with you. It works best paired with an AI receptionist for calls that can be answered by voice, and with a person ready to pick up the reply.', ['Decide which calls should trigger the text, such as calls unanswered after a set number of rings or after hours', 'Write a short message in your own words that says who you are and asks what the caller needs', 'Add opt-out wording and check the message with your own advisor', 'Decide who receives the reply and how quickly they must respond', 'Test the flow from your own phone before it goes live', 'Review the replies weekly and adjust the wording'], ['A text does not help if nobody picks up the reply.', 'Emergency callers may prefer a call back, so offer that as well.', 'Messages must follow consent and carrier rules, which vary.', 'Not every missed call is a customer. Some are wrong numbers or sales calls.'], ['/services/missed-call-text-back', '/services/ai-receptionist', '/industries/plumbing', '/industries/hvac', '/industries/roofing'], '2026-09-18'),
  guide('is-an-ai-receptionist-worth-it', 'Is an AI receptionist worth it for a small business?', 'A plain way to decide whether an AI receptionist is worth it for your business, with the numbers to check and the cases where it is not.', 'It is worth it when missed calls cost you more than the service does, and when the calls you miss are real customers. A quick test: estimate how many calls you miss in a week, what one new customer is worth, and how many of those customers you could realistically win back. If that figure is clearly above what the service costs, it is worth a trial. If you rarely miss calls, or your callers always want one particular person, a receptionist may not help much.', ['Count the calls you miss in a typical week, including after hours', 'Work out what a new customer is worth to you, not just the first job', 'Use the missed call calculator with cautious assumptions', 'Ask what the receptionist does when it cannot answer and how it hands over to a person', 'Ask for the disclosure wording, the contract terms and how to cancel', 'Test with real call scenarios before relying on it'], ['An AI receptionist will not suit callers who insist on speaking to a particular person.', 'It needs clear rules and testing, so setup time is part of the cost.', 'Calculator results are estimates, not promises of recovered revenue.', 'Ask any provider about overage charges and contract length before signing.'], ['/resources/missed-call-text-back-calculator', '/services/ai-receptionist', '/resources/ai-receptionist-vs-answering-service'], '2026-09-18'),
  guide('missed-call-text-back-calculator', 'Missed call text-back calculator', 'Estimate the potential value of responding to missed calls faster, then review the call path behind the estimate.', 'This calculator is a simple planning tool. Enter your own weekly missed-call count, average job value, and a cautious recovery assumption to estimate the size of the opportunity worth investigating. It does not predict revenue, bookings, or results.', ['Check your phone records for missed or abandoned calls', 'Use a realistic average completed-job value', 'Choose a conservative recovery assumption', 'Review whether calls can be answered, texted back, or routed faster', 'Measure the actual outcome after changes go live'], ['Not every missed call is a qualified job opportunity.', 'A fast text does not replace an available, well-trained team.', 'Any SMS workflow needs approved messaging, consent, and opt-out handling.'], ['/services/missed-call-text-back', '/services/ai-receptionist', '/services/lead-follow-up'], '2026-09-16'),
  guide('ai-receptionist-vs-answering-service', 'AI receptionist vs. traditional answering service', 'A practical comparison for service businesses deciding how to handle after-hours and overflow calls.', 'An AI receptionist can follow configured intake, routing, and booking rules continuously. A traditional answering service relies on human agents and may be a better fit when a live person, complex judgment, or a particular coverage model matters.', ['Map the calls that currently go unanswered', 'Separate routine questions from calls needing a person', 'Define escalation and disclosure rules', 'Compare coverage, training, reporting, and maintenance needs', 'Test the chosen process with real call scenarios'], ['AI systems require careful configuration and escalation boundaries.', 'Traditional services may offer human judgment but can vary in training and availability.', 'Neither option replaces licensed, emergency, or business-critical human decision-making.'], ['/services/ai-receptionist', '/services/missed-call-text-back']),
  guide('missed-call-text-back', 'How missed-call text back works for service businesses', 'A plain-language guide to fast SMS acknowledgement after an unanswered business call.', 'Missed-call text back sends a configured SMS acknowledgement after a call is not answered. The aim is to offer a clear next step while the team is unavailable, not to pretend a person has replied.', ['Missed call is detected', 'Approved SMS acknowledgement is sent', 'Customer can reply or take a booking action', 'Response is routed to the team or workflow', 'A human handles exceptions and complex requests'], ['Messages must follow consent, carrier, and communication rules.', 'The message needs an obvious way to reach a person when needed.', 'A text back does not solve an unstaffed or poorly routed lead process by itself.'], ['/services/missed-call-text-back', '/services/lead-follow-up']),
  guide('review-automation', 'How review automation works without review gating', 'A practical guide to requesting authentic customer reviews after completed service.', 'Review automation uses a completion signal and a respectful request path to ask every eligible customer for honest feedback. It should not filter customers based on sentiment, buy reviews, or suppress legitimate criticism.', ['Define a legitimate completion event', 'Choose the relevant review channel for the industry', 'Send a clear, neutral request', 'Use a limited, respectful follow-up', 'Route reviews and response tasks to the team'], ['Review policies differ by platform and can change.', 'More requests do not guarantee more positive reviews.', 'The operational experience must improve alongside the request process.'], ['/services/review-automation', '/services/reputation-management']),
  guide('crm-vs-field-service-management', 'CRM vs. field-service management software', 'How service businesses can decide which system should own leads, jobs, and customer follow-up.', 'A CRM is usually built to manage customer relationships and sales activity. Field-service software is generally built around scheduling, technicians, jobs, and operational delivery. Many service businesses need both, connected around defined handoffs rather than forced into one tool.', ['List where leads arrive', 'Identify who owns qualification and booking', 'Identify who owns scheduling and job completion', 'Map data that must pass between systems', 'Define the source of truth for each customer stage'], ['Replacing an operational platform can be more disruptive than connecting around it.', 'Duplicate records and unclear ownership create errors.', 'Integration feasibility depends on the actual tools, permissions, and connection methods available.'], ['/services/crm-automation', '/integrations']),
  guide('cold-email-infrastructure', 'What cold email infrastructure includes', 'A buyer guide to responsible outbound email setup and the limits of deliverability work.', 'Cold email infrastructure is the technical and operational setup behind responsible outreach: sending domains, inboxes, authentication, sending controls, list quality, and reply handling. It cannot guarantee inbox placement, replies, meetings, or sales.', ['Define audience and outreach purpose', 'Set up domains and inboxes responsibly', 'Configure authentication records', 'Prepare list quality and opt-out handling', 'Launch cautiously and monitor replies, bounces, and complaints'], ['Technical setup does not make irrelevant outreach acceptable.', 'Deliverability changes over time and depends on recipient systems.', 'Legal, privacy, and platform obligations must be reviewed for the intended campaign.'], ['/services/cold-email-infrastructure', '/services/outbound-lead-generation']),
  guide('zapier-vs-n8n', 'Zapier vs. n8n for service-business automation', 'A neutral comparison of two common automation approaches for maintainable business workflows.', 'Zapier can be a practical choice for straightforward, managed app-to-app workflows. n8n can offer more flexibility and control for teams prepared to manage a more technical setup. The right option depends on the workflow, available integrations, security needs, ownership, and maintenance capacity.', ['Define the trigger, data, and desired outcome', 'Check available connection methods', 'Design exception and approval paths', 'Choose the owner who will maintain the workflow', 'Test with realistic failures as well as successful runs'], ['Zapier may be simpler for common workflows but costs and limits vary by plan.', 'n8n may offer more control but can require more technical ownership.', 'Neither tool removes the need for process design, monitoring, and human escalation.'], ['/integrations/zapier', '/integrations/n8n', '/services/crm-automation']),
  guide('measuring-lead-generation-results', 'How to measure lead generation results', 'Define bounce rate, positive replies, qualified meetings, response time and booking rate before judging a lead-generation system.', 'Start with a baseline and a written definition of a qualified lead. Count unique people rather than repeated messages. Keep campaign traffic separate from warm-up, test and internal activity, and trace qualified meetings to CRM records. These are measurement methods, not claims about LYCORE client results.', ['Choose a reporting period, such as 30 days, and record the dates', 'Agree who qualifies, what counts as a reply and how duplicate leads are removed', 'Record the baseline from the sending platform, call system, website analytics and CRM', 'Report each count with its denominator and source', 'Compare equivalent periods and note changes in audience, budget or seasonality', 'Publish a case study only with verified records and permission to share'], ['A positive reply rate needs a stated denominator; different platforms may calculate it differently.', 'Email delivery acceptance does not establish inbox placement. Warm-up activity is not prospect engagement.', 'Booked meetings, attended meetings and paid work are separate outcomes. Report them separately.', 'Missing tracking is unknown data, not zero performance. Small samples need their counts shown.'], ['/services/outbound-lead-generation', '/services/cold-email-infrastructure', '/services/lead-follow-up', '/services/web-design']),
];

export const resourcesHub: PageMeta = { path: '/resources', label: 'Resources', title: 'Service Business Growth Resources — LYCORE', description: 'Practical guides on call response, follow-up, reviews, CRM workflows, outbound systems, and automation choices.', h1: 'Make the next step clear.', kind: 'resource', updatedAt: '2026-09-11' };
